<?php
/**
 * @file jj_business_articles.info
 *
 * Provides blocks with a form field to search by an exposed argument.
 *
 * @author Jon Kamke <jkamke@nerdery.com>
 */

/**
 * Implements hook_block_info().
 */
function jj_search_blocks_info() {
  $blocks['business_type'] = array(
    'info' => t('Syndicate'),
  );
  $blocks['rating'] = array(
    'info' => t('Syndicate'),
  );
  $blocks['amenity'] = array(
    'info' => t('Syndicate'),
  );
}

/**
 * Implements hook_block_view().
 */
function jj_search_blocks_view($delta) {
  $block = array();

  switch($delta) {
    case 'business_type':
      $block['subject'] = t('Search By Business Type');
      $block['content'] = array(
        '#theme' => 'jj_search_blocks_business_type',
        '#title' => t('Search By Business Type'),
        '#content' => jj_search_blocks_business_type_form(),
      );
      break;
    case 'rating':
      $block['subject'] = t('Search By Rating');
      $block['content'] = array(
        '#theme' => 'jj_search_blocks_rating',
        '#title' => t('Search By Rating'),
        '#content' => jj_search_blocks_rating_form(),
      );
      break;
    case 'amenity':
      $block['subject'] = t('Search By Amenity');
      $block['content'] = array(
        '#theme' => 'jj_search_blocks_amenity',
        '#title' => t('Search By Amenity'),
        '#content' => jj_search_blocks_amenity(),
      );
      break;
  }

  return $block;
}

/**
 * Implements hook_theme()
 */
function jj_search_blocks_theme() {
  return array(
    'jj_search_blocks_business_type' => array(
      'variables' => array('content' => NULL),
      'path' => drupal_get_path('module', 'jj_search_blocks') . '/templates',
      'template' => 'jj-search-blocks-business-type',
    ),
    'jj_search_blocks_rating' => array(
      'variables' => array('content' => NULL),
      'path' => drupal_get_path('module', 'jj_search_blocks') . '/templates',
      'template' => 'jj-search-blocks-rating',
    ),
    'jj_search_blocks_amenity' => array(
      'variables' => array('content' => NULL),
      'path' => drupal_get_path('module', 'jj_search_blocks') . '/templates',
      'template' => 'jj-search-blocks-amenity',
    ),
  );
}

/**
 * Form to search by business type.
 *
 * @see jj_search_blocks_view()
 */
function jj_search_blocks_business_type_form() {
  $form = array();

  $form['business_type'] = array(
    '#type' => '',
    '#title' => t('Search by Business Type'),
  );

  return $form;
}

/**
 * Form to search by rating.
 *
 * @see jj_search_blocks_view()
 */
function jj_search_blocks_rating_form() {
  $form = array();

  $form['rating'] = array(
    '#type' => 'select',
    '#title' => t('Search by Rating'),
    '#options' => array(
      1 => t('1'),
      2 => t('2'),
      3 => t('3'),
      4 => t('4'),
      5 => t('5'),
    ),
  );

  return $form;
}

/**
 * Form to search by amenity.
 *
 * @see jj_search_blocks_view()
 */
function jj_search_blocks_amenity() {
  $form = array();

  $form['amenity'] = array(
    '#type' => '',
    '#title' => t(''),
  );

  return $form;
}
